from dataclasses import dataclass


@dataclass(frozen=True)
class Question:
    identifier: str
    section: str
    level: str
    prompt: str
    choices: tuple[str, str, str, str]
    correct_choice: int
    explanation: str
    passage: str = ""


@dataclass(frozen=True)
class WritingPrompt:
    identifier: str
    task: str
    target_words: str
    prompt: str
    checklist: tuple[str, ...]


QUESTION_BANK = (
    Question("s01", "structures", "B2", "Bien qu'il ___ déjà tard, ils ont poursuivi le débat.", ("est", "soit", "fût", "sera"), 1, "Après « bien que », on emploie le subjonctif : « soit ».") ,
    Question("s02", "structures", "B2", "Il a accepté le poste, ___ les conditions soient moins favorables qu'espéré.", ("quoique", "pourvu que", "à moins que", "si bien que"), 0, "« Quoique » marque la concession et se construit avec le subjonctif.") ,
    Question("s03", "structures", "C1", "Ce n'est pas tant son idée qui est contestée ___ la manière dont elle a été imposée.", ("que", "mais", "comme", "donc"), 0, "La corrélation correcte est « non pas tant… que… » / « pas tant… que… ».") ,
    Question("s04", "structures", "C1", "À supposer qu'elle ___ raison, cela ne justifierait pas son ton.", ("a", "ait", "avait", "aurait"), 1, "« À supposer que » introduit le subjonctif : « ait ».") ,
    Question("s05", "structures", "B2", "Il parle comme s'il ___ personnellement cette époque.", ("avait connue", "connaissait", "a connu", "connaîtra"), 1, "Après « comme si », on utilise l'imparfait pour une situation irréelle au présent.") ,
    Question("s06", "structures", "C1", "Les mesures entreront en vigueur ___ l'Assemblée les aura adoptées.", ("dès que", "alors que", "tandis que", "bien que"), 0, "« Dès que » exprime l'antériorité immédiate : futur + futur antérieur.") ,
    Question("s07", "structures", "B2", "Cette décision a été prise ___ de réduire les dépenses inutiles.", ("en vue", "à force", "faute", "quant"), 0, "« En vue de » signifie « dans le but de ».") ,
    Question("s08", "structures", "C1", "Son exposé était clair, ___ quelques raccourcis discutables.", ("hormis", "d'autant que", "pour autant", "afin que"), 0, "« Hormis » signifie « à l'exception de » et introduit ici un groupe nominal.") ,
    Question("s09", "structures", "B2", "Je ne vois pas ___ il faudrait renoncer si vite.", ("ce que", "ce dont", "pourquoi", "duquel"), 2, "Le verbe « renoncer » appelle « à » ; ici, on demande la raison : « pourquoi ».") ,
    Question("s10", "structures", "C1", "Encore faudrait-il que cette proposition ___ applicable sur le terrain.", ("est", "soit", "sera", "était"), 1, "L'inversion avec « encore faudrait-il » est suivie du subjonctif.") ,
    Question("s11", "structures", "B2", "Ils se sont finalement mis d'accord, ___ leurs désaccords initiaux.", ("en dépit de", "grâce à", "auprès de", "à l'égard de"), 0, "« En dépit de » exprime l'opposition : malgré leurs désaccords.") ,
    Question("s12", "structures", "C1", "Il n'est pas exclu que le projet ___ avant la fin de l'année.", ("aboutit", "aboutisse", "aboutirait", "a abouti"), 1, "« Il n'est pas exclu que » appelle le subjonctif.") ,
    Question("s13", "structures", "B2", "La conférence, ___ je devais intervenir, a été reportée.", ("dont", "où", "que", "laquelle"), 1, "On intervient « à » une conférence ; « où » reprend le cadre événementiel.") ,
    Question("s14", "structures", "C1", "Il a refusé, non ___ le projet manquait d'intérêt, mais parce qu'il était irréalisable.", ("que", "pas que", "seulement que", "sans que"), 0, "La tournure est « non que + subjonctif », qui écarte une cause supposée.") ,
    Question("s15", "structures", "C1", "Pour peu que chacun y mette du sien, l'accord ___ possible.", ("devient", "deviendrait", "deviendra", "soit devenu"), 1, "« Pour peu que » pose une condition ; la conséquence hypothétique se met au conditionnel.") ,
    Question("s16", "structures", "B2", "Elle a fini par céder, ___ elle y était longtemps opposée.", ("alors même qu'", "de sorte qu'", "si bien qu'", "à condition qu'"), 0, "« Alors même que » renforce une opposition ou une concession.") ,
    Question("s17", "structures", "C1", "L'auteur nuance son propos afin qu'on ne lui ___ pas une position trop catégorique.", ("attribue", "attribuait", "attribuera", "a attribué"), 0, "« Afin que » est suivi du subjonctif : « attribue ».") ,
    Question("s18", "structures", "C1", "Le directeur a tenu à ce que les résultats lui ___ directement transmis.", ("sont", "soient", "seraient", "avaient été"), 1, "« Tenir à ce que » exige le subjonctif ; la forme passive est « soient transmis ».") ,
    Question("r01", "lecture", "B2", "Quelle est l'idée principale du texte ?", ("Le télétravail doit être supprimé.", "Le télétravail exige un nouveau cadre collectif.", "Les bureaux n'ont plus aucune utilité.", "Les salariés préfèrent tous travailler chez eux."), 1, "Le texte met en avant un équilibre à construire, pas une suppression ni une généralisation.", "Depuis la généralisation du travail à distance, les entreprises cherchent moins à compter les jours passés au bureau qu'à préserver la circulation de l'information. Les équipes qui alternent présence et distance doivent expliciter ce qui, autrefois, se transmettait spontanément près de la machine à café. Le défi n'est donc pas de choisir un camp, mais d'inventer des rituels communs."),
    Question("r02", "lecture", "B2", "Que suggère l'expression « se transmettait spontanément » ?", ("Une règle écrite était appliquée.", "Des informations circulaient de manière informelle.", "Les salariés suivaient une formation obligatoire.", "Les réunions étaient trop nombreuses."), 1, "Le passage oppose les échanges informels d'avant à la nécessité actuelle de les expliciter.", "Depuis la généralisation du travail à distance, les entreprises cherchent moins à compter les jours passés au bureau qu'à préserver la circulation de l'information. Les équipes qui alternent présence et distance doivent expliciter ce qui, autrefois, se transmettait spontanément près de la machine à café. Le défi n'est donc pas de choisir un camp, mais d'inventer des rituels communs."),
    Question("r03", "lecture", "C1", "Quelle réserve l'auteur formule-t-il sur les indicateurs écologiques ?", ("Ils sont tous manipulés.", "Ils ne permettent aucune comparaison.", "Ils peuvent masquer les effets déplacés ailleurs.", "Ils coûtent trop cher à produire."), 2, "L'auteur critique une lecture isolée des chiffres, qui peut ignorer les effets indirects.", "Une ville peut se féliciter d'avoir réduit ses déchets visibles sans avoir diminué son empreinte réelle. Si elle exporte une partie de ses rebuts ou externalise la production des biens qu'elle consomme, le bilan local s'améliore tandis que la pression environnementale se déplace. Les indicateurs restent utiles, à condition de ne pas les confondre avec la réalité qu'ils tentent de mesurer."),
    Question("r04", "lecture", "C1", "Dans « à condition de ne pas les confondre », « les » désigne :", ("les villes", "les déchets", "les indicateurs", "les réalités"), 2, "Le pronom reprend le dernier groupe nominal pertinent : « les indicateurs ».", "Une ville peut se féliciter d'avoir réduit ses déchets visibles sans avoir diminué son empreinte réelle. Si elle exporte une partie de ses rebuts ou externalise la production des biens qu'elle consomme, le bilan local s'améliore tandis que la pression environnementale se déplace. Les indicateurs restent utiles, à condition de ne pas les confondre avec la réalité qu'ils tentent de mesurer."),
    Question("r05", "lecture", "B2", "Pourquoi l'association demande-t-elle une médiation ?", ("Elle refuse tout projet immobilier.", "Elle souhaite revoir le calendrier et les garanties.", "Elle veut annuler une réunion publique.", "Elle cherche un financement européen."), 1, "Elle ne rejette pas le projet en bloc ; elle conteste ses modalités et demande des garanties.", "Dans un communiqué, l'association de quartier affirme ne pas être hostile à la rénovation de la place centrale. Elle regrette toutefois que le calendrier des travaux ait été annoncé avant la concertation avec les commerçants. Elle demande désormais une médiation afin d'obtenir des engagements précis sur l'accès aux boutiques pendant le chantier."),
    Question("r06", "lecture", "C1", "Le ton du communiqué est surtout :", ("ironique", "nuancé et revendicatif", "indifférent", "triomphal"), 1, "Le texte concède l'intérêt de la rénovation tout en formulant une demande précise.", "Dans un communiqué, l'association de quartier affirme ne pas être hostile à la rénovation de la place centrale. Elle regrette toutefois que le calendrier des travaux ait été annoncé avant la concertation avec les commerçants. Elle demande désormais une médiation afin d'obtenir des engagements précis sur l'accès aux boutiques pendant le chantier."),
    Question("r07", "lecture", "C1", "Que veut dire « à rebours d'une idée reçue » ?", ("En confirmant une opinion fréquente.", "En allant contre une croyance répandue.", "En revenant à une méthode ancienne.", "En refusant toute preuve scientifique."), 1, "« À rebours de » signifie « dans le sens opposé à ».", "À rebours d'une idée reçue, l'abondance de données ne garantit pas une meilleure décision. Lorsque les critères sont mal définis, multiplier les tableaux de bord peut donner une impression de précision tout en éloignant l'organisation des questions essentielles. La compétence décisive consiste alors moins à produire des chiffres qu'à formuler le problème avec rigueur."),
    Question("r08", "lecture", "C1", "Selon l'auteur, quelle compétence est décisive ?", ("Collecter le plus de données possible.", "Créer davantage de tableaux de bord.", "Définir précisément le problème.", "Automatiser toutes les décisions."), 2, "La dernière phrase oppose la production de chiffres à la formulation rigoureuse du problème.", "À rebours d'une idée reçue, l'abondance de données ne garantit pas une meilleure décision. Lorsque les critères sont mal définis, multiplier les tableaux de bord peut donner une impression de précision tout en éloignant l'organisation des questions essentielles. La compétence décisive consiste alors moins à produire des chiffres qu'à formuler le problème avec rigueur."),
    Question("r09", "lecture", "B2", "Quel bénéfice du prêt d'objets est mis en avant ?", ("Il remplace les commerces locaux.", "Il permet d'éviter des achats ponctuels.", "Il rend les objets plus luxueux.", "Il supprime les besoins de réparation."), 1, "La bibliothèque d'objets évite l'achat d'un équipement peu utilisé.", "La bibliothèque d'objets du quartier prête désormais une perceuse, une machine à coudre et du matériel de camping. Son objectif n'est pas de dissuader les habitants de posséder quoi que ce soit, mais de proposer une alternative pour les équipements utilisés rarement. Les responsables espèrent aussi que l'atelier de réparation voisin deviendra un lieu de transmission de savoir-faire."),
    Question("r10", "lecture", "C1", "L'atelier de réparation est présenté comme :", ("un concurrent de la bibliothèque", "un lieu possible de partage des compétences", "un service réservé aux professionnels", "une solution pour produire davantage"), 1, "Le texte évoque explicitement la « transmission de savoir-faire ».", "La bibliothèque d'objets du quartier prête désormais une perceuse, une machine à coudre et du matériel de camping. Son objectif n'est pas de dissuader les habitants de posséder quoi que ce soit, mais de proposer une alternative pour les équipements utilisés rarement. Les responsables espèrent aussi que l'atelier de réparation voisin deviendra un lieu de transmission de savoir-faire."),
    Question("r11", "lecture", "C1", "La thèse de l'éditorial est que :", ("la lenteur administrative est toujours inutile", "la rapidité doit être conciliée avec le débat", "le débat public empêche toute action", "les élus doivent décider seuls"), 1, "L'éditorial refuse l'opposition simpliste entre efficacité et discussion démocratique.", "On reproche volontiers au débat public de ralentir l'action. Pourtant, une décision prise vite mais mal comprise risque de rencontrer, plus tard, une opposition qui la retarde davantage encore. Consulter ne signifie pas renoncer à décider ; c'est souvent la condition pour que la décision soit comprise, amendée si nécessaire, puis durablement appliquée."),
    Question("r12", "lecture", "C1", "Quel enchaînement logique est défendu ?", ("Décider, puis expliquer si nécessaire.", "Consulter, décider, puis appliquer durablement.", "Renoncer à décider dès qu'une opposition apparaît.", "Reporter toute mesure jusqu'à l'unanimité."), 1, "Le passage décrit une consultation qui améliore l'acceptation et l'application de la décision.", "On reproche volontiers au débat public de ralentir l'action. Pourtant, une décision prise vite mais mal comprise risque de rencontrer, plus tard, une opposition qui la retarde davantage encore. Consulter ne signifie pas renoncer à décider ; c'est souvent la condition pour que la décision soit comprise, amendée si nécessaire, puis durablement appliquée."),
    Question("r13", "lecture", "B2", "Quelle évolution des entreprises est décrite ?", ("Elles imposent davantage de jours au bureau.", "Elles privilégient la circulation de l'information.", "Elles abandonnent tous les bureaux.", "Elles diminuent le nombre de réunions."), 1, "La première phrase oppose le comptage des jours au besoin de faire circuler l'information.", "Depuis la généralisation du travail à distance, les entreprises cherchent moins à compter les jours passés au bureau qu'à préserver la circulation de l'information. Les équipes qui alternent présence et distance doivent expliciter ce qui, autrefois, se transmettait spontanément près de la machine à café. Le défi n'est donc pas de choisir un camp, mais d'inventer des rituels communs."),
    Question("r14", "lecture", "C1", "Quelle mesure correspondrait le mieux à la conclusion du texte ?", ("Interdire le télétravail.", "Créer des temps d'échange communs, sur place et à distance.", "Évaluer chaque salarié uniquement par sa présence.", "Supprimer toute communication informelle."), 1, "Des « rituels communs » répondent précisément au défi énoncé par l'auteur.", "Depuis la généralisation du travail à distance, les entreprises cherchent moins à compter les jours passés au bureau qu'à préserver la circulation de l'information. Les équipes qui alternent présence et distance doivent expliciter ce qui, autrefois, se transmettait spontanément près de la machine à café. Le défi n'est donc pas de choisir un camp, mais d'inventer des rituels communs."),
    Question("r15", "lecture", "C1", "L'expression « se féliciter » implique surtout que la ville :", ("se critique sévèrement", "se réjouit d'un résultat", "ignore ses statistiques", "change de maire"), 1, "Se féliciter de quelque chose signifie s'en réjouir ou s'en satisfaire.", "Une ville peut se féliciter d'avoir réduit ses déchets visibles sans avoir diminué son empreinte réelle. Si elle exporte une partie de ses rebuts ou externalise la production des biens qu'elle consomme, le bilan local s'améliore tandis que la pression environnementale se déplace. Les indicateurs restent utiles, à condition de ne pas les confondre avec la réalité qu'ils tentent de mesurer."),
    Question("r16", "lecture", "B2", "Quelle conclusion peut-on tirer du texte ?", ("Les chiffres écologiques sont inutiles.", "Un bon bilan local prouve un bon bilan global.", "Il faut interpréter les chiffres dans un contexte plus large.", "Les villes ne doivent plus gérer leurs déchets."), 2, "Le texte ne rejette pas les indicateurs ; il demande de les interpréter avec prudence.", "Une ville peut se féliciter d'avoir réduit ses déchets visibles sans avoir diminué son empreinte réelle. Si elle exporte une partie de ses rebuts ou externalise la production des biens qu'elle consomme, le bilan local s'améliore tandis que la pression environnementale se déplace. Les indicateurs restent utiles, à condition de ne pas les confondre avec la réalité qu'ils tentent de mesurer."),
    Question("r17", "lecture", "C1", "Que risque de produire l'externalisation évoquée ?", ("Une baisse automatique de la consommation.", "Un déplacement géographique de l'impact environnemental.", "La disparition des déchets.", "Une hausse des emplois municipaux."), 1, "L'impact ne disparaît pas : il est déplacé hors du territoire observé.", "Une ville peut se féliciter d'avoir réduit ses déchets visibles sans avoir diminué son empreinte réelle. Si elle exporte une partie de ses rebuts ou externalise la production des biens qu'elle consomme, le bilan local s'améliore tandis que la pression environnementale se déplace. Les indicateurs restent utiles, à condition de ne pas les confondre avec la réalité qu'ils tentent de mesurer."),
    Question("r18", "lecture", "B2", "Quelle critique l'association adresse-t-elle à la municipalité ?", ("Elle refuse la rénovation elle-même.", "Elle a annoncé les travaux avant la concertation.", "Elle a fermé toutes les boutiques.", "Elle a supprimé la médiation."), 1, "La chronologie est critiquée : l'annonce est venue avant l'échange avec les commerçants.", "Dans un communiqué, l'association de quartier affirme ne pas être hostile à la rénovation de la place centrale. Elle regrette toutefois que le calendrier des travaux ait été annoncé avant la concertation avec les commerçants. Elle demande désormais une médiation afin d'obtenir des engagements précis sur l'accès aux boutiques pendant le chantier."),
    Question("r19", "lecture", "C1", "Sur quel sujet l'association veut-elle des garanties ?", ("Le choix des matériaux.", "L'accès aux commerces pendant le chantier.", "Le nom de la place.", "La durée des réunions."), 1, "La demande porte explicitement sur l'accès aux boutiques pendant les travaux.", "Dans un communiqué, l'association de quartier affirme ne pas être hostile à la rénovation de la place centrale. Elle regrette toutefois que le calendrier des travaux ait été annoncé avant la concertation avec les commerçants. Elle demande désormais une médiation afin d'obtenir des engagements précis sur l'accès aux boutiques pendant le chantier."),
    Question("r20", "lecture", "B2", "Dans le texte, « toutefois » sert à :", ("ajouter une conséquence", "introduire une réserve", "donner un exemple", "conclure le raisonnement"), 1, "« Toutefois » marque ici une opposition entre l'accord de principe et la critique formulée.", "Dans un communiqué, l'association de quartier affirme ne pas être hostile à la rénovation de la place centrale. Elle regrette toutefois que le calendrier des travaux ait été annoncé avant la concertation avec les commerçants. Elle demande désormais une médiation afin d'obtenir des engagements précis sur l'accès aux boutiques pendant le chantier."),
    Question("r21", "lecture", "C1", "Quelle opposition structure le texte sur les données ?", ("Quantité des données / qualité de la question posée.", "Données locales / données internationales.", "Décision humaine / décision juridique.", "Passé / avenir."), 0, "L'auteur oppose l'accumulation de chiffres à la définition rigoureuse du problème.", "À rebours d'une idée reçue, l'abondance de données ne garantit pas une meilleure décision. Lorsque les critères sont mal définis, multiplier les tableaux de bord peut donner une impression de précision tout en éloignant l'organisation des questions essentielles. La compétence décisive consiste alors moins à produire des chiffres qu'à formuler le problème avec rigueur."),
    Question("r22", "lecture", "C1", "Pourquoi les tableaux de bord peuvent-ils être trompeurs ?", ("Ils contiennent toujours des erreurs de calcul.", "Ils peuvent donner une apparence de précision sans clarifier l'essentiel.", "Ils sont réservés aux grandes entreprises.", "Ils empêchent de mesurer les résultats."), 1, "Le texte parle d'une « impression de précision » qui détourne des questions essentielles.", "À rebours d'une idée reçue, l'abondance de données ne garantit pas une meilleure décision. Lorsque les critères sont mal définis, multiplier les tableaux de bord peut donner une impression de précision tout en éloignant l'organisation des questions essentielles. La compétence décisive consiste alors moins à produire des chiffres qu'à formuler le problème avec rigueur."),
    Question("r23", "lecture", "B2", "Que peut-on déduire de l'objectif de la bibliothèque ?", ("Elle encourage l'achat d'objets neufs.", "Elle propose un usage partagé pour certains équipements.", "Elle vend des machines réparées.", "Elle ne prête que des livres."), 1, "Les objets sont prêtés pour éviter d'acheter un équipement rarement utilisé.", "La bibliothèque d'objets du quartier prête désormais une perceuse, une machine à coudre et du matériel de camping. Son objectif n'est pas de dissuader les habitants de posséder quoi que ce soit, mais de proposer une alternative pour les équipements utilisés rarement. Les responsables espèrent aussi que l'atelier de réparation voisin deviendra un lieu de transmission de savoir-faire."),
    Question("r24", "lecture", "C1", "Quelle affirmation serait contraire au texte ?", ("Certains objets peuvent être empruntés.", "La possession individuelle est interdite.", "L'atelier peut transmettre des compétences.", "L'alternative concerne des équipements rarement utilisés."), 1, "Le texte précise au contraire qu'il ne s'agit pas de dissuader toute possession individuelle.", "La bibliothèque d'objets du quartier prête désormais une perceuse, une machine à coudre et du matériel de camping. Son objectif n'est pas de dissuader les habitants de posséder quoi que ce soit, mais de proposer une alternative pour les équipements utilisés rarement. Les responsables espèrent aussi que l'atelier de réparation voisin deviendra un lieu de transmission de savoir-faire."),
    Question("r25", "lecture", "C1", "Pourquoi une décision mal comprise peut-elle ralentir l'action ?", ("Elle coûte nécessairement moins cher.", "Elle provoque plus tard une opposition.", "Elle est automatiquement annulée.", "Elle oblige à consulter tous les citoyens."), 1, "Le texte établit une conséquence différée : l'incompréhension nourrit une opposition ultérieure.", "On reproche volontiers au débat public de ralentir l'action. Pourtant, une décision prise vite mais mal comprise risque de rencontrer, plus tard, une opposition qui la retarde davantage encore. Consulter ne signifie pas renoncer à décider ; c'est souvent la condition pour que la décision soit comprise, amendée si nécessaire, puis durablement appliquée."),
    Question("r26", "lecture", "B2", "Selon le texte, consulter signifie :", ("abandonner toute décision", "faire voter chaque détail", "préparer une décision mieux comprise", "retarder systématiquement un projet"), 2, "L'auteur affirme que consulter ne revient pas à renoncer à décider.", "On reproche volontiers au débat public de ralentir l'action. Pourtant, une décision prise vite mais mal comprise risque de rencontrer, plus tard, une opposition qui la retarde davantage encore. Consulter ne signifie pas renoncer à décider ; c'est souvent la condition pour que la décision soit comprise, amendée si nécessaire, puis durablement appliquée."),
    Question("r27", "lecture", "C1", "Dans ce contexte, « amendée » veut dire :", ("annulée", "modifiée", "imposée", "accélérée"), 1, "Amender une décision, c'est la modifier ou l'améliorer sur certains points.", "On reproche volontiers au débat public de ralentir l'action. Pourtant, une décision prise vite mais mal comprise risque de rencontrer, plus tard, une opposition qui la retarde davantage encore. Consulter ne signifie pas renoncer à décider ; c'est souvent la condition pour que la décision soit comprise, amendée si nécessaire, puis durablement appliquée."),
    Question("r28", "lecture", "C1", "Le texte adopte principalement une stratégie argumentative de :", ("caricature de l'opinion adverse", "réfutation nuancée d'une idée courante", "description chronologique", "témoignage personnel"), 1, "Il part d'un reproche fréquent et le nuance par une conséquence possible et un raisonnement.", "On reproche volontiers au débat public de ralentir l'action. Pourtant, une décision prise vite mais mal comprise risque de rencontrer, plus tard, une opposition qui la retarde davantage encore. Consulter ne signifie pas renoncer à décider ; c'est souvent la condition pour que la décision soit comprise, amendée si nécessaire, puis durablement appliquée."),
    Question("r29", "lecture", "C1", "Quelle reformulation respecte le mieux la dernière phrase ?", ("La consultation rend toute décision impossible.", "Une décision durable peut nécessiter une consultation préalable.", "La consultation remplace l'application d'une décision.", "Il faut attendre l'unanimité avant d'agir."), 1, "C'est la synthèse fidèle du lien établi entre consultation, compréhension et application durable.", "On reproche volontiers au débat public de ralentir l'action. Pourtant, une décision prise vite mais mal comprise risque de rencontrer, plus tard, une opposition qui la retarde davantage encore. Consulter ne signifie pas renoncer à décider ; c'est souvent la condition pour que la décision soit comprise, amendée si nécessaire, puis durablement appliquée."),
)


WRITING_PROMPTS = (
    WritingPrompt("w1", "Tâche 1 — message", "60–120 mots", "Vous avez suivi un atelier professionnel très utile. Écrivez au responsable pour le remercier, expliquer ce qui vous a été le plus utile et suggérer une amélioration.", ("Respectez le destinataire et le but.", "Donnez deux informations concrètes.", "Terminez par une formule adaptée.")),
    WritingPrompt("w2", "Tâche 2 — article", "120–150 mots", "Pour le site de votre ville, racontez une expérience de bénévolat et expliquez ce qu'elle vous a appris. Encouragez d'autres habitants à participer.", ("Organisez le récit dans le temps.", "Ajoutez votre opinion argumentée.", "Employez des connecteurs variés.")),
    WritingPrompt("w3", "Tâche 3 — synthèse et avis", "120–180 mots", "Document A : « Le travail hybride donne davantage d'autonomie. » Document B : « Il fragilise la cohésion des équipes. » Rédigez un texte qui compare ces deux points de vue puis donne votre position.", ("Présentez les deux points de vue équitablement.", "Nuancez : concession, limite, exemple.", "Concluez avec une position claire.")),
    WritingPrompt("w4", "Tâche 3 — synthèse et avis", "120–180 mots", "Document A : « Les villes doivent limiter la circulation automobile au centre. » Document B : « Ces restrictions pénalisent les personnes qui n'ont pas d'alternative. » Comparez et donnez votre avis.", ("Évitez le simple pour/contre.", "Reformulez les documents.", "Proposez une condition ou une solution.")),
    WritingPrompt("w5", "Tâche 2 — courrier", "120–150 mots", "Écrivez à la direction de votre établissement après l'annonce de la suppression d'un espace de travail. Décrivez l'usage de cet espace, exprimez votre désaccord et proposez une solution réaliste.", ("Adoptez un registre formel.", "Distinguez faits, opinion et demande.", "Formulez une proposition précise.")),
    WritingPrompt("w6", "Tâche 1 — message", "60–120 mots", "Un ami hésite à accepter une formation loin de chez lui. Répondez-lui : demandez des précisions, donnez votre avis et suggérez une façon de prendre sa décision.", ("Adaptez le registre à un ami.", "Posez au moins une question.", "Justifiez votre conseil.")),
)


CONNECTORS = (
    "certes… mais", "dans la mesure où", "toutefois", "en revanche",
    "de surcroît", "à cet égard", "autrement dit", "dès lors",
    "à supposer que", "pour autant", "en définitive", "nonobstant",
)
